# REST API configuration
host: ${oc.env:API_HOST,0.0.0.0}
port: ${oc.env:API_PORT,8000}
workers: ${oc.env:API_WORKERS,1}
reload: ${oc.env:API_RELOAD,false}
log_level: ${oc.env:API_LOG_LEVEL,info}
cors_origins: ${oc.env:CORS_ORIGINS,["*"]}
max_request_size_mb: ${oc.env:MAX_REQUEST_SIZE_MB,10}