# Logging configuration
log_path: ${oc.env:LOG_PATH,/var/log/supervisor}
log_level: ${oc.env:LOG_LEVEL,INFO}
max_bytes: ${oc.env:LOG_MAX_BYTES,10485760}  # 10MB
backup_count: ${oc.env:LOG_BACKUP_COUNT,3}
format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"