# Production Configuration for Qdrant MCP
# Optimized for security and performance

# Qdrant database configuration
qdrant:
  host: localhost
  port: 6333
  grpc_port: 6334
  # Use persistent volumes in production
  data_path: /data/qdrant/storage
  snapshots_path: /data/qdrant/snapshots
  max_payload_size_mb: 5
  telemetry_disabled: true

# Vector database configuration
vector:
  collection_name: claude_vectors
  embedding_model: all-MiniLM-L6-v2
  vector_size: 384
  distance_metric: cosine
  max_tokens: 512
  top_k: 20
  min_score: 0.3
  # Enable on-disk payload for large datasets
  on_disk_payload: true
  indexed_only: true

# REST API configuration
api:
  # Bind to localhost in production, use reverse proxy
  host: 127.0.0.1
  port: 8000
  workers: 4
  reload: false
  log_level: warning
  cors_origins:
    - "https://your-domain.com"
    - "https://app.your-domain.com"
  max_request_size_mb: 50

# MCP server configuration
mcp:
  server_name: qdrant-mcp
  server_version: 1.0.0
  port: 8001
  protocol_version: 2024-11-05

# Logging configuration
logging:
  log_path: /var/log/qdrant-mcp
  log_level: WARNING
  max_bytes: 52428800  # 50MB
  backup_count: 10
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Security configuration
security:
  # Generate with: openssl rand -base64 32
  api_key: "YOUR_SECURE_API_KEY_HERE"
  enable_tls: true
  tls_cert_path: /etc/ssl/certs/server.crt
  tls_key_path: /etc/ssl/private/server.key
  allowed_ips:
    - "10.0.0.0/8"
    - "172.16.0.0/12"
    - "192.168.0.0/16"
  rate_limit_per_minute: 100