name: Update Dependencies

on:
  schedule:
    # Run every Monday at 9am UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Update dependencies
        id: update
        run: |
          # Update all dependencies to latest versions
          uv pip compile pyproject.toml --upgrade -o uv.lock
          
          # Check if there are changes
          if git diff --quiet; then
            echo "No dependency updates available"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "Dependencies updated"
            echo "has_changes=true" >> $GITHUB_OUTPUT
            
            # Generate update summary
            git diff uv.lock | grep "^[+-]" | grep -v "^[+-]#" | head -20 > updates.txt
          fi

      - name: Run tests with updated dependencies
        if: steps.update.outputs.has_changes == 'true'
        run: |
          uv pip install --system -e ".[dev]"
          uv run pytest tests/

      - name: Create Pull Request
        if: steps.update.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update dependencies'
          title: 'chore: automated dependency updates'
          body: |
            ## Automated Dependency Updates
            
            This PR contains automated dependency updates generated by uv.
            
            ### Changes
            ```diff
            $(cat updates.txt || echo "See full diff in Files changed tab")
            ```
            
            ### Checklist
            - [ ] All tests pass
            - [ ] No breaking changes identified
            - [ ] Security advisories reviewed
            
            ---
            *This PR was automatically generated by the dependency update workflow.*
          branch: deps/automated-update
          delete-branch: true
          labels: |
            dependencies
            automated